apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project-tools
  labels:
    app: backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/markusintility/projecttools-backend:bc58c3c472f38fa81b66f1d7d8392a6892924bfb
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: projecttools-secrets
                  key: database-url
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
