apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: project-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_LOG_DIR
              value: "/var/opt/mssql/log"
            - name: MSSQL_DATA_DIR
              value: "/var/opt/mssql/data"
            - name: MSSQL_BACKUP_DIR
              value: "/var/opt/mssql/backup"
            - name: MSSQL_DUMP_DIR
              value: "/var/opt/mssql/dump"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: sa-password
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: mssql-system
              mountPath: /.system
            - name: mssql-log
              mountPath: /log
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
        - name: mssql-system
          emptyDir: {}
        - name: mssql-log
          emptyDir: {}
