apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projecttools
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/MarkusIntility/ProjectTools-
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc  # bytt ut med kluster-URL hvis ekstern
    namespace: project-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: projecttools-secrets
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: mssql-secret
      jsonPointers:
        - /data
